### ISSUE TITLE
[Desenvolvimento] Visualização de lista específica

### ISSUE THREAD

**Issue by DevCaua** [Caua539/chepa#50]
O usuário deve ser capaz de visualizar o nome de cada lista; o supermercado definido; o orçamento de cada lista de compra; o "Valor Disponível" - correspondente a quanto ainda há disponível do orçamento para a compra; o sub-total da compra; o valor unitário de cada item comprado e o produto do valor unitário com as quantidades de cada item.

Obs.: Telas apresentadas nos protótipos PTR-009 e PTR-010

Pontos: 15

**Comment by NataliaMarufuji** [comment]
done

**Comment by NataliaMarufuji** [comment]
done
