### ISSUE TITLE
[Desenvolvimento] Atualização de lista específica

### ISSUE THREAD

**Issue by DevCaua** [Caua539/chepa#51]
O usuário deve ser capaz de definir quantas unidades e o valor unitário de cada item comprado, o sistema deve calcular o valor final por item, apresentá-lo ao usuário e subtrair do "Valor Disponível".

Os campos como: quantidade, item, valor, supermercado e orçamento poderão ser atualizados

Pontos: 15

**Comment by NataliaMarufuji** [comment]
done
